language: node_js
node_js:
  - "8"

install:
  - npm install

script: 
  - npm test

deploy:
  skip_cleanup: true
  provider: script
  script: bash script/docs_auto_deploy.sh
  on:
    branch: master
